### ISSUE TITLE
Release `go-daash` v0.2.0

### ISSUE THREAD

**Issue by 0xRampey** [stackrlabs/go-daash#10]
`go-daash` : v0.2.0

- [x] Refactor and update DA interface (Makes it easier for Vulcan and SDK to work with)
- https://github.com/stackrlabs/go-daash/pull/11
- [x] DA verification libraries for Celestia, Avail
- https://github.com/stackrlabs/Internal-Project-Tracking/issues/43
- https://github.com/stackrlabs/Internal-Project-Tracking/issues/41

- [ ] Switch from `goldberg` to `turing` on Avail 

- [ ] Update to blob daddy and announcement!

**Comment by kautukkundan** [comment]
Create "Update to blob daddy" ticket @0xRampey

**Comment by 0xRampey** [comment]
https://github.com/stackrlabs/go-daash/issues/12
